rafyu6dof_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - base_to_shoulder
    - shoulder1_to_lower_arm
    - lower_arm_to_upper_arm
    - upper_arm_to_wrist
    - wrist_to_hand
    - hand_to_hand_rotate
    - grip_1_extension
    - grip_2_extension
  gains:
    base_to_shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder1_to_lower_arm:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    lower_arm_to_upper_arm:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    upper_arm_to_wrist:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_to_hand:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    hand_to_hand_rotate:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    grip_1_extension:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    grip_2_extension:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - hand_to_hand_rotate
    - grip_1_extension
  gains:
    hand_to_hand_rotate:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    grip_1_extension:
      p: 100
      d: 1
      i: 1
      i_clamp: 1