controller_list:
  - name: rafyu6dof_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - base_to_shoulder
      - shoulder1_to_lower_arm
      - lower_arm_to_upper_arm
      - upper_arm_to_wrist
      - wrist_to_hand
      - hand_to_hand_rotate
      - grip_1_extension
      - grip_2_extension
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - hand_to_hand_rotate
      - grip_1_extension